CIS174_TestCoreApp/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIS174_TestCoreApp.Models
{
	public class Student
	{
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Grade { get; set; }
		
		// If sufficient access doesn't exist
		public Student(string firstName, string lastName)
		{
			FirstName = firstName;
			LastName = lastName;
		}
		public Student(string firstName, string lastName, string grade)
		{
			FirstName = firstName;
			LastName = lastName;
			Grade = grade;
		}
	}
}

CIS174_TestCoreApp/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CIS174_TestCoreApp.Models;

namespace CIS174_TestCoreApp.Controllers
{
	public class AssignmentController : Controller
	{
		[Route("Assignment/{permission?}")]
		public IActionResult Index(int permission = 1)
		{
			ViewBag.PermissionId = permission;

			List<Student> studentData = new List<Student>();
			studentData.Add(new Student("Mike", "Dylan", "B"));
			studentData.Add(new Student("Gabe", "Smith", "A+"));
			studentData.Add(new Student("Jerome", "Rivers", "F"));
			studentData.Add(new Student("Donnie", "Troomp", "Expelled"));

			return View("Index", studentData);
		}
	}
}

CIS174_TestCoreApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CIS174_TestCoreApp.Models;
using CIS174_TestCoreApp.Controllers;

namespace CIS174_TestCoreApp.Controllers
{
	public class HomeController : Controller
	{

		[Route("/")]
		public IActionResult Index()
		{
			return View();
		}
	}
}

CIS174_TestCoreApp/Views/Assignment/Index.cshtml
@model List<Student>
@{ 
    ViewData["Title"] = "Permission";
}

<h1>Assignment 6.1 Student Data</h1>
@if (ViewBag.PermissionId <= 1)
{
    <label>You do not have access to view this data.</label>
}
else if ((ViewBag.PermissionId >= 2) && (ViewBag.PermissionId < 8))
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var student in Model)
            {
            <tr>
                <td>@student.FirstName</td>
                <td>@student.LastName</td>
            </tr>
            }
        </tbody>
    </table>
}
else if(ViewBag.PermissionId >= 8 && ViewBag.PermissionId <= 10)
{
    <label>Hey, Welcome to being a powerful Admin!</label>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model)
            {
            <tr>
                <td>@student.FirstName</td>
                <td>@student.LastName</td>
                <td>@student.Grade</td>
             </tr>
            }
        </tbody>
    </table>
}

CIS174_TestCoreApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h1>Home Page</h1>

CIS174_TestCoreApp/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/custom.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="dropdown nav-item">
                            <ul class="dropdown-menu">
                                <li><a class="nav-link bg-dark text-light" asp-controller="Assignment" asp-action="Index">Assignment 6.1</a></li>
                            </ul>
                            <a class="nav-link bg-dark dropdown-toggle text-light" data-toggle="dropdown" role="navigation" aria-haspopup="true"
                               aria-expanded="false">Assignments<span class="caret"></span></a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>